/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editeurtext;

import com.sun.glass.ui.CommonDialogs;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javafx.stage.FileChooser;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import jdk.management.resource.internal.ApproverGroup;

/**
 *
 * @author admin
 */
public class EditeurTxt extends javax.swing.JFrame {

    /**
     * Creates new form EditeurTxt
     */
    public EditeurTxt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblt = new javax.swing.JLabel();
        btnc = new javax.swing.JButton();
        cmb = new javax.swing.JComboBox<>();
        spinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtar = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menuf = new javax.swing.JMenu();
        btno = new javax.swing.JMenuItem();
        btns = new javax.swing.JMenuItem();
        btnq = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblt.setBackground(new java.awt.Color(255, 255, 255));
        lblt.setText("     Taille");
        lblt.setOpaque(true);

        btnc.setBackground(new java.awt.Color(102, 255, 255));
        btnc.setText("Couleur");
        btnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncActionPerformed(evt);
            }
        });

        cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Felix Titling", "Footlight MT Light", "Forte", "Franklin Gothic Book", " " }));
        cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbActionPerformed(evt);
            }
        });

        spinner.setModel(new javax.swing.SpinnerNumberModel(20, 0, 40, 2));
        spinner.setMaximumSize(new java.awt.Dimension(20, 20));
        spinner.setMinimumSize(new java.awt.Dimension(0, 0));

        txtar.setBackground(new java.awt.Color(255, 204, 255));
        txtar.setColumns(20);
        txtar.setRows(5);
        jScrollPane1.setViewportView(txtar);

        Menuf.setText("File");
        Menuf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenufActionPerformed(evt);
            }
        });

        btno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        btno.setText("Ouvrire");
        btno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoActionPerformed(evt);
            }
        });
        Menuf.add(btno);

        btns.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        btns.setText("Sauvegarder");
        btns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsActionPerformed(evt);
            }
        });
        Menuf.add(btns);

        btnq.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        btnq.setText("Quitter");
        btnq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqActionPerformed(evt);
            }
        });
        Menuf.add(btnq);

        jMenuBar1.add(Menuf);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb, 0, 146, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnc)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnc)
                    .addComponent(cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoActionPerformed
       JFileChooser choix =new JFileChooser();
       choix.setCurrentDirectory(new File("."));
       FileNameExtensionFilter filter =new FileNameExtensionFilter("Fichiers texte", "txt");
       choix.setFileFilter(filter);
       int rep = choix.showOpenDialog(null);
       if(rep == JFileChooser.APPROVE_OPTION){
           try {
               File fichier = new File(choix.getSelectedFile().getAbsolutePath());
               Scanner sc = new Scanner(fichier);
               while (sc.hasNext()) {
                   String line = sc.nextLine();
                   txtar.append(line + "\n");

               }
           } catch (FileNotFoundException ffe) {
               ffe.printStackTrace();
           }
       }
        
        
    }//GEN-LAST:event_btnoActionPerformed
    
    private void btncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncActionPerformed
        JColorChooser choix = new JColorChooser();
        Color couleur = choix.showDialog(null, "choisir une couleur", Color.BLACK);
        txtar.setForeground(couleur);
        
       
        
    }//GEN-LAST:event_btncActionPerformed

    private void cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbActionPerformed
       txtar.setFont(new Font(cmb.getSelectedItem().toString(),Font.BOLD, (int) spinner.getValue()));
       //txtar.setFont(new Font);
    }//GEN-LAST:event_cmbActionPerformed

    private void MenufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenufActionPerformed
          
    }//GEN-LAST:event_MenufActionPerformed

    private void btnqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqActionPerformed
     System.exit(0);
    }//GEN-LAST:event_btnqActionPerformed

    private void btnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsActionPerformed
        JFileChooser choix = new JFileChooser();
        choix.setCurrentDirectory(new File("."));
        int repo =choix.showSaveDialog(null);
        if (repo==JFileChooser.APPROVE_OPTION){
            File fichier = new File(choix.getSelectedFile().getAbsolutePath());
            try {
                FileWriter fw = new FileWriter(fichier,true);
                fw.write("\n"+txtar.getText());
                fw.close();
                JOptionPane.showMessageDialog(this," le contenue enregestrer dans "+fichier.getAbsolutePath(),"sauvgarder", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException iOException) {
            }
        }
    }//GEN-LAST:event_btnsActionPerformed

    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditeurTxt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menuf;
    private javax.swing.JButton btnc;
    private javax.swing.JMenuItem btno;
    private javax.swing.JMenuItem btnq;
    private javax.swing.JMenuItem btns;
    private javax.swing.JComboBox<String> cmb;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblt;
    private javax.swing.JSpinner spinner;
    private javax.swing.JTextArea txtar;
    // End of variables declaration//GEN-END:variables
}
