/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editeurtext;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author admin
 */
public class EditeurDEtexte extends javax.swing.JDialog {

    /**
     * Creates new form EditeurDEtexte
     */
    public EditeurDEtexte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltaille = new javax.swing.JLabel();
        spinner = new javax.swing.JSpinner();
        cmbpolice = new javax.swing.JComboBox<>();
        btncouleur = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtar = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuo = new javax.swing.JMenuItem();
        menus = new javax.swing.JMenuItem();
        menuq = new javax.swing.JMenuItem();
        menua = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbltaille.setBackground(new java.awt.Color(153, 255, 255));
        lbltaille.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbltaille.setText("    Taille");
        lbltaille.setOpaque(true);

        spinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spinner.setModel(new javax.swing.SpinnerNumberModel(20, 0, 40, 2));

        cmbpolice.setBackground(new java.awt.Color(153, 255, 255));
        cmbpolice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbpolice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Felix Titling", "Footlight MT Light", "Forte", "Franklin Gothic Book" }));
        cmbpolice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpoliceActionPerformed(evt);
            }
        });

        btncouleur.setBackground(new java.awt.Color(153, 255, 255));
        btncouleur.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btncouleur.setText("Couleur");
        btncouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncouleurActionPerformed(evt);
            }
        });

        txtar.setColumns(20);
        txtar.setRows(5);
        jScrollPane1.setViewportView(txtar);

        jMenu1.setText("Fichier");

        menuo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuo.setText("Ouvrire");
        menuo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuoActionPerformed(evt);
            }
        });
        jMenu1.add(menuo);

        menus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menus.setText("Sauvgarder");
        menus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusActionPerformed(evt);
            }
        });
        jMenu1.add(menus);

        menuq.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuq.setText("Quitter");
        menuq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuqActionPerformed(evt);
            }
        });
        jMenu1.add(menuq);

        jMenuBar1.add(jMenu1);

        menua.setText(" Apropos");
        jMenuBar1.add(menua);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbltaille, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbpolice, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btncouleur)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltaille, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbpolice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncouleur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncouleurActionPerformed
       JColorChooser choix = new JColorChooser();
       Color couleur = choix.showDialog(null, "choisir une couleur", Color.BLACK);
       txtar.setForeground(couleur);
    }//GEN-LAST:event_btncouleurActionPerformed

    private void cmbpoliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpoliceActionPerformed
        txtar.setFont(new Font((String) cmbpolice.getSelectedItem(), Font.BOLD, (int) spinner.getValue()));
    }//GEN-LAST:event_cmbpoliceActionPerformed

    private void menuqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuqActionPerformed

        System.exit(0);
    }//GEN-LAST:event_menuqActionPerformed

    private void menuoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuoActionPerformed
        JFileChooser choix =new JFileChooser();
        choix.setCurrentDirectory(new File("."));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Fichiers texte", "txt");
        choix.setFileFilter(filter);
        int reponse =choix.showOpenDialog(null);
        if (reponse == JFileChooser.APPROVE_OPTION){
            File fichier =new File(choix.getSelectedFile().getAbsolutePath());
            txtar.setText("");
            try {
                Scanner sc = new Scanner(fichier);
                while (sc.hasNext()) {
                    String line = sc.nextLine();
                    txtar.append(line+"\n");
                }
                sc.close();
            } catch (FileNotFoundException ffe) {
                ffe.printStackTrace();
            }
        }
    }//GEN-LAST:event_menuoActionPerformed

    private void menusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusActionPerformed
         JFileChooser choix = new JFileChooser();
         choix.setCurrentDirectory(new File("."));
         int rep= choix.showSaveDialog(null);
         if (rep==JFileChooser.APPROVE_OPTION){
             try {
                 File fichier = new File(choix.getSelectedFile().getAbsolutePath());
                 FileWriter fw = new FileWriter(fichier,true);
                 
                 fw.write(txtar.getText());
                 fw.close();
             } catch (IOException ioe) {
                 ioe.printStackTrace();
             }
         }
    }//GEN-LAST:event_menusActionPerformed

  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditeurDEtexte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditeurDEtexte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditeurDEtexte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditeurDEtexte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditeurDEtexte dialog = new EditeurDEtexte(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncouleur;
    private javax.swing.JComboBox<String> cmbpolice;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltaille;
    private javax.swing.JMenu menua;
    private javax.swing.JMenuItem menuo;
    private javax.swing.JMenuItem menuq;
    private javax.swing.JMenuItem menus;
    private javax.swing.JSpinner spinner;
    private javax.swing.JTextArea txtar;
    // End of variables declaration//GEN-END:variables
}
