/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tps;

/**
 *
 * @author admin
 */
public class coursb extends javax.swing.JFrame {

   String message1;   String message2;
   String message3; String message4;
   private static int cpt=0;

    public coursb() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        btnKawtar = new javax.swing.JRadioButton();
        btnOlaya = new javax.swing.JRadioButton();
        btnHassnae = new javax.swing.JRadioButton();
        btnanass = new javax.swing.JRadioButton();
        Text = new javax.swing.JTextField();
        resultat = new javax.swing.JLabel();
        btnFin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(btnKawtar);
        btnKawtar.setText("Kawtar");
        btnKawtar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKawtarActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnOlaya);
        btnOlaya.setText("Olaya");
        btnOlaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOlayaActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnHassnae);
        btnHassnae.setText("Hassnae");
        btnHassnae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHassnaeActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnanass);
        btnanass.setText("Anass");
        btnanass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanassActionPerformed(evt);
            }
        });

        Text.setBackground(new java.awt.Color(153, 255, 255));
        Text.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 51, 51));
        Text.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        resultat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        resultat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnFin.setText("End;");
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Text, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHassnae)
                    .addComponent(btnanass)
                    .addComponent(btnOlaya)
                    .addComponent(btnKawtar)
                    .addComponent(btnFin))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnanass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHassnae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKawtar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOlaya, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFin)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHassnaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHassnaeActionPerformed
        message1=" you are the life mmm";
        Text.setText(message1);
    }//GEN-LAST:event_btnHassnaeActionPerformed

    private void btnOlayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlayaActionPerformed
        // TODO add your handling code here:
          message1=" you are Amazing mmm ";
                  Text.setText(message1);

    }//GEN-LAST:event_btnOlayaActionPerformed

    private void btnanassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanassActionPerformed
        // TODO add your handling code here
        message1=" your are my best Friend mmm";
                Text.setText(message1);

    }//GEN-LAST:event_btnanassActionPerformed

    private void btnKawtarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKawtarActionPerformed
        // TODO add your handling code here:
        message1="your the best mmm";
                Text.setText(message1);

    }//GEN-LAST:event_btnKawtarActionPerformed

    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
        // TODO add your handling code here:
        cpt++;
        if(cpt==1){
        message1=" Fhal t9ol 3ndi mohiba f Hyperbole HHHHHHHHH";
        resultat.setText(message1);
        }else if(cpt==2) {
                    message2=" just Kidding ,you are my Friends Ooh";
        resultat.setText(message2);

        }
    }//GEN-LAST:event_btnFinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coursb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coursb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coursb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coursb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coursb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Text;
    private javax.swing.JButton btnFin;
    private javax.swing.JRadioButton btnHassnae;
    private javax.swing.JRadioButton btnKawtar;
    private javax.swing.JRadioButton btnOlaya;
    private javax.swing.JRadioButton btnanass;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel resultat;
    // End of variables declaration//GEN-END:variables
}
